<!-- $Id: start.htm 17216 2011-01-19 06:03:12Z liubo $ -->
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<title>SHOP 管理中心</title>
<meta name="robots" content="noindex, nofollow">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<link href="<?=_PUBLIC?>/styles/general.css" rel="stylesheet" type="text/css" />
<link href="<?=_PUBLIC?>/styles/main.css" rel="stylesheet" type="text/css" />
</head>
<body>

<h1>
<span class="action-span1"><a href="index.php?act=main">SHOP 管理中心</a> </span><span id="search_id" class="action-span1"></span>
<div style="clear:both"></div>
</h1>
<!-- directory install start -->

<?php  foreach($admins as $ad):   ?>
<ul id="<?php echo $ad->admin_id; ?>" style="padding:0; margin: 0; list-style-type:none; color: #CC0000;">
<?php echo $ad->admin_name; ?>
<?php echo "&nbsp;&nbsp;&nbsp;&nbsp;" .$ad->email; ?>
</ul>
<?php  endforeach;  ?>
<div class="list-div">

</div>

<div id="footer">

FOR PRACTICE -  - </div>

</div>

</body>
</html>